// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheRepository creates a new instance of MockCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheRepository {
	mock := &MockCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheRepository is an autogenerated mock type for the CacheRepository type
type MockCacheRepository struct {
	mock.Mock
}

type MockCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheRepository) EXPECT() *MockCacheRepository_Expecter {
	return &MockCacheRepository_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCacheRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockCacheRepository_Expecter) Close() *MockCacheRepository_Close_Call {
	return &MockCacheRepository_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockCacheRepository_Close_Call) Run(run func()) *MockCacheRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCacheRepository_Close_Call) Return(err error) *MockCacheRepository_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheRepository_Close_Call) RunAndReturn(run func() error) *MockCacheRepository_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCacheRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockCacheRepository_Expecter) Delete(ctx interface{}, key interface{}) *MockCacheRepository_Delete_Call {
	return &MockCacheRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockCacheRepository_Delete_Call) Run(run func(ctx context.Context, key string)) *MockCacheRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheRepository_Delete_Call) Return(err error) *MockCacheRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockCacheRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) Get(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacheRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockCacheRepository_Expecter) Get(ctx interface{}, key interface{}) *MockCacheRepository_Get_Call {
	return &MockCacheRepository_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockCacheRepository_Get_Call) Run(run func(ctx context.Context, key string)) *MockCacheRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheRepository_Get_Call) Return(bytes []byte, err error) *MockCacheRepository_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCacheRepository_Get_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *MockCacheRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) Set(ctx context.Context, key string, value []byte, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCacheRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx
//   - key
//   - value
//   - ttl
func (_e *MockCacheRepository_Expecter) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockCacheRepository_Set_Call {
	return &MockCacheRepository_Set_Call{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *MockCacheRepository_Set_Call) Run(run func(ctx context.Context, key string, value []byte, ttl time.Duration)) *MockCacheRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockCacheRepository_Set_Call) Return(err error) *MockCacheRepository_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheRepository_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte, ttl time.Duration) error) *MockCacheRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}
