// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/OzkrOssa/franchi-api/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFranchiseRepository creates a new instance of MockFranchiseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFranchiseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFranchiseRepository {
	mock := &MockFranchiseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFranchiseRepository is an autogenerated mock type for the FranchiseRepository type
type MockFranchiseRepository struct {
	mock.Mock
}

type MockFranchiseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFranchiseRepository) EXPECT() *MockFranchiseRepository_Expecter {
	return &MockFranchiseRepository_Expecter{mock: &_m.Mock}
}

// CreateFranchise provides a mock function for the type MockFranchiseRepository
func (_mock *MockFranchiseRepository) CreateFranchise(ctx context.Context, franchise *domain.Franchise) (*domain.Franchise, error) {
	ret := _mock.Called(ctx, franchise)

	if len(ret) == 0 {
		panic("no return value specified for CreateFranchise")
	}

	var r0 *domain.Franchise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Franchise) (*domain.Franchise, error)); ok {
		return returnFunc(ctx, franchise)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Franchise) *domain.Franchise); ok {
		r0 = returnFunc(ctx, franchise)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Franchise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Franchise) error); ok {
		r1 = returnFunc(ctx, franchise)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFranchiseRepository_CreateFranchise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFranchise'
type MockFranchiseRepository_CreateFranchise_Call struct {
	*mock.Call
}

// CreateFranchise is a helper method to define mock.On call
//   - ctx
//   - franchise
func (_e *MockFranchiseRepository_Expecter) CreateFranchise(ctx interface{}, franchise interface{}) *MockFranchiseRepository_CreateFranchise_Call {
	return &MockFranchiseRepository_CreateFranchise_Call{Call: _e.mock.On("CreateFranchise", ctx, franchise)}
}

func (_c *MockFranchiseRepository_CreateFranchise_Call) Run(run func(ctx context.Context, franchise *domain.Franchise)) *MockFranchiseRepository_CreateFranchise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Franchise))
	})
	return _c
}

func (_c *MockFranchiseRepository_CreateFranchise_Call) Return(franchise1 *domain.Franchise, err error) *MockFranchiseRepository_CreateFranchise_Call {
	_c.Call.Return(franchise1, err)
	return _c
}

func (_c *MockFranchiseRepository_CreateFranchise_Call) RunAndReturn(run func(ctx context.Context, franchise *domain.Franchise) (*domain.Franchise, error)) *MockFranchiseRepository_CreateFranchise_Call {
	_c.Call.Return(run)
	return _c
}

// GetFranchiseByID provides a mock function for the type MockFranchiseRepository
func (_mock *MockFranchiseRepository) GetFranchiseByID(ctx context.Context, id uint64) (*domain.Franchise, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFranchiseByID")
	}

	var r0 *domain.Franchise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*domain.Franchise, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *domain.Franchise); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Franchise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFranchiseRepository_GetFranchiseByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFranchiseByID'
type MockFranchiseRepository_GetFranchiseByID_Call struct {
	*mock.Call
}

// GetFranchiseByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockFranchiseRepository_Expecter) GetFranchiseByID(ctx interface{}, id interface{}) *MockFranchiseRepository_GetFranchiseByID_Call {
	return &MockFranchiseRepository_GetFranchiseByID_Call{Call: _e.mock.On("GetFranchiseByID", ctx, id)}
}

func (_c *MockFranchiseRepository_GetFranchiseByID_Call) Run(run func(ctx context.Context, id uint64)) *MockFranchiseRepository_GetFranchiseByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockFranchiseRepository_GetFranchiseByID_Call) Return(franchise *domain.Franchise, err error) *MockFranchiseRepository_GetFranchiseByID_Call {
	_c.Call.Return(franchise, err)
	return _c
}

func (_c *MockFranchiseRepository_GetFranchiseByID_Call) RunAndReturn(run func(ctx context.Context, id uint64) (*domain.Franchise, error)) *MockFranchiseRepository_GetFranchiseByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFranchise provides a mock function for the type MockFranchiseRepository
func (_mock *MockFranchiseRepository) UpdateFranchise(ctx context.Context, franchise *domain.Franchise) (*domain.Franchise, error) {
	ret := _mock.Called(ctx, franchise)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFranchise")
	}

	var r0 *domain.Franchise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Franchise) (*domain.Franchise, error)); ok {
		return returnFunc(ctx, franchise)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Franchise) *domain.Franchise); ok {
		r0 = returnFunc(ctx, franchise)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Franchise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Franchise) error); ok {
		r1 = returnFunc(ctx, franchise)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFranchiseRepository_UpdateFranchise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFranchise'
type MockFranchiseRepository_UpdateFranchise_Call struct {
	*mock.Call
}

// UpdateFranchise is a helper method to define mock.On call
//   - ctx
//   - franchise
func (_e *MockFranchiseRepository_Expecter) UpdateFranchise(ctx interface{}, franchise interface{}) *MockFranchiseRepository_UpdateFranchise_Call {
	return &MockFranchiseRepository_UpdateFranchise_Call{Call: _e.mock.On("UpdateFranchise", ctx, franchise)}
}

func (_c *MockFranchiseRepository_UpdateFranchise_Call) Run(run func(ctx context.Context, franchise *domain.Franchise)) *MockFranchiseRepository_UpdateFranchise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Franchise))
	})
	return _c
}

func (_c *MockFranchiseRepository_UpdateFranchise_Call) Return(franchise1 *domain.Franchise, err error) *MockFranchiseRepository_UpdateFranchise_Call {
	_c.Call.Return(franchise1, err)
	return _c
}

func (_c *MockFranchiseRepository_UpdateFranchise_Call) RunAndReturn(run func(ctx context.Context, franchise *domain.Franchise) (*domain.Franchise, error)) *MockFranchiseRepository_UpdateFranchise_Call {
	_c.Call.Return(run)
	return _c
}
