// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/OzkrOssa/franchi-api/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFranchiseService creates a new instance of MockFranchiseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFranchiseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFranchiseService {
	mock := &MockFranchiseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFranchiseService is an autogenerated mock type for the FranchiseService type
type MockFranchiseService struct {
	mock.Mock
}

type MockFranchiseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFranchiseService) EXPECT() *MockFranchiseService_Expecter {
	return &MockFranchiseService_Expecter{mock: &_m.Mock}
}

// CreateNewFranchise provides a mock function for the type MockFranchiseService
func (_mock *MockFranchiseService) CreateNewFranchise(ctx context.Context, franchise *domain.Franchise) (*domain.Franchise, error) {
	ret := _mock.Called(ctx, franchise)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewFranchise")
	}

	var r0 *domain.Franchise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Franchise) (*domain.Franchise, error)); ok {
		return returnFunc(ctx, franchise)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Franchise) *domain.Franchise); ok {
		r0 = returnFunc(ctx, franchise)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Franchise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Franchise) error); ok {
		r1 = returnFunc(ctx, franchise)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFranchiseService_CreateNewFranchise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewFranchise'
type MockFranchiseService_CreateNewFranchise_Call struct {
	*mock.Call
}

// CreateNewFranchise is a helper method to define mock.On call
//   - ctx
//   - franchise
func (_e *MockFranchiseService_Expecter) CreateNewFranchise(ctx interface{}, franchise interface{}) *MockFranchiseService_CreateNewFranchise_Call {
	return &MockFranchiseService_CreateNewFranchise_Call{Call: _e.mock.On("CreateNewFranchise", ctx, franchise)}
}

func (_c *MockFranchiseService_CreateNewFranchise_Call) Run(run func(ctx context.Context, franchise *domain.Franchise)) *MockFranchiseService_CreateNewFranchise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Franchise))
	})
	return _c
}

func (_c *MockFranchiseService_CreateNewFranchise_Call) Return(franchise1 *domain.Franchise, err error) *MockFranchiseService_CreateNewFranchise_Call {
	_c.Call.Return(franchise1, err)
	return _c
}

func (_c *MockFranchiseService_CreateNewFranchise_Call) RunAndReturn(run func(ctx context.Context, franchise *domain.Franchise) (*domain.Franchise, error)) *MockFranchiseService_CreateNewFranchise_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFranchise provides a mock function for the type MockFranchiseService
func (_mock *MockFranchiseService) UpdateFranchise(ctx context.Context, franchise *domain.Franchise) (*domain.Franchise, error) {
	ret := _mock.Called(ctx, franchise)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFranchise")
	}

	var r0 *domain.Franchise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Franchise) (*domain.Franchise, error)); ok {
		return returnFunc(ctx, franchise)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Franchise) *domain.Franchise); ok {
		r0 = returnFunc(ctx, franchise)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Franchise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Franchise) error); ok {
		r1 = returnFunc(ctx, franchise)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFranchiseService_UpdateFranchise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFranchise'
type MockFranchiseService_UpdateFranchise_Call struct {
	*mock.Call
}

// UpdateFranchise is a helper method to define mock.On call
//   - ctx
//   - franchise
func (_e *MockFranchiseService_Expecter) UpdateFranchise(ctx interface{}, franchise interface{}) *MockFranchiseService_UpdateFranchise_Call {
	return &MockFranchiseService_UpdateFranchise_Call{Call: _e.mock.On("UpdateFranchise", ctx, franchise)}
}

func (_c *MockFranchiseService_UpdateFranchise_Call) Run(run func(ctx context.Context, franchise *domain.Franchise)) *MockFranchiseService_UpdateFranchise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Franchise))
	})
	return _c
}

func (_c *MockFranchiseService_UpdateFranchise_Call) Return(franchise1 *domain.Franchise, err error) *MockFranchiseService_UpdateFranchise_Call {
	_c.Call.Return(franchise1, err)
	return _c
}

func (_c *MockFranchiseService_UpdateFranchise_Call) RunAndReturn(run func(ctx context.Context, franchise *domain.Franchise) (*domain.Franchise, error)) *MockFranchiseService_UpdateFranchise_Call {
	_c.Call.Return(run)
	return _c
}
